### ISSUE TITLE
Live Forms throws error when embedded in a Live Accordion tab

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#1266]
**Product & Version**
Vanjaro for DNN 1.0.5 on DNN 9.9.1 

**Describe the bug**
A Live Forms entity that contains a checkbox list control displays fine on a Vanjaro page, but when it's embedded within a Live Accordion pane, it crashes the page. It's probably not a factor, but the LA pane containing the LF form was set to be initially collapsed when the page loads.

**To Reproduce**
1. Create a Live Form and add a checkbox list with a couple of options
2. Publish the page
3. Add a Live Accordion, and embed the Form into the pane.
4. Publish the page
5. If the page displays the form without error, edit the Accordion pane to be collapsed on initial display
6. Publish the page and check results

**Current behavior**
The page stops loading when the Live Accordion / Live Forms content is encountered..

**Additional context**
The URL includes the following: error=Unable+to+cast+object+of+type+%27Mandeeps.DNN.Modules.LiveForms.UI.WebControls.DynamicCheckBoxList%27+to+type+%27System.Web.UI.HtmlControls.HtmlInputHidden%27.&content=0

and event log has:

InnerStackTrace:

   at DotNetNuke.UI.Utilities.ClientAPI.GetDNNVariableControl(Control objParent)
   at DotNetNuke.UI.Utilities.ClientAPI.RegisterDNNVariableControl(Control objParent)
   at DotNetNuke.UI.Utilities.ClientAPI.GetClientVariableList(Page objPage)
   at DotNetNuke.UI.Utilities.ClientAPI.RegisterClientVariable(Page objPage, String strVar, String strValue, Boolean blnOverwrite)
   at DotNetNuke.Framework.JavaScriptLibraries.JavaScript.RegisterClientReference(Page page, ClientNamespaceReferences reference)
   at DotNetNuke.Framework.ServicesFrameworkImpl.RegisterAjaxScript(Page page)
   at DotNetNuke.Framework.CDefault.RegisterAjaxScript()
   at DotNetNuke.Framework.DefaultPage.OnPreRender(EventArgs evt)
   at System.Web.UI.Control.<PreRenderRecursiveInternalAsync>d__249.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()

**Comment by hshimanshusharma** [comment]
@eswanzey This issue has been fixed in Live Accordion you will get an updated accordion which will release soon.
