### ISSUE TITLE
Skin Error -- problems with Temp files

### ISSUE THREAD

**Issue by jfre11** [vanjarosoftware/Vanjaro.Platform#1954]
Im  using DNN 9.10.2 with Vanjaro 1.2

I have 4 websites for 1 DNN instance and they all  work fine until a recompile is triggered  -- then all the website go down.    I'm getting the following from my log file.   I then delete everything in the TEMP folder and the websites come back up and stay up until a recompile occors:   I have  the vanjaro skin in my default portal settings-- 

2021-12-04 21:09:28,281 [JFDell][Thread:34][ERROR] Vanjaro.Common.Engines.UIEngine.AngularBootstrap.Controllers.CommonRazorController - Vanjaro Common Pre Compile Razor Templates Started at 12/5/2021 5:09:28 AM .
2021-12-04 21:09:28,307 [JFDell][Thread:34][ERROR] Vanjaro.Common.Engines.UIEngine.AngularBootstrap.Controllers.CommonRazorController - Vanjaro Common Pre Compile Razor Templates Completed In 0 Seconds at 12/5/2021 5:09:28 AM .
2021-12-04 21:12:43,426 [JFDell][Thread:34][ERROR] DotNetNuke.Services.Exceptions.Exceptions - DotNetNuke.Services.Exceptions.PageLoadException: Unhandled error loading page. ---> System.InvalidOperationException: No service for type 'DotNetNuke.UI.Modules.IModuleControlPipeline' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at DotNetNuke.UI.Skins.Skin..ctor() in D:\a\1\s\DNN Platform\Library\UI\Skins\Skin.cs:line 71
   at Vanjaro.Skin.Base..ctor()
   at ASP.portals__default_skins_vanjaro_base_ascx..ctor() in c:\Users\jenni\AppData\Local\Temp\Temporary ASP.NET Files\vs\ada252ef\35188155\App_Web_5cgeb5sl.0.cs:line 0
   at __ASP.FastObjectFactory_app_web_5cgeb5sl.Create_ASP_portals__default_skins_vanjaro_base_ascx() in c:\Users\jenni\AppData\Local\Temp\Temporary ASP.NET Files\vs\ada252ef\35188155\App_Web_5cgeb5sl.1.cs:line 0
   at System.Web.Compilation.BuildResultCompiledType.CreateInstance()
   at System.Web.UI.TemplateControl.LoadControl(IWebObjectFactory objectFactory, VirtualPath virtualPath, Type t, Object[] parameters)
   at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath)
   at DotNetNuke.UI.ControlUtilities.LoadControl[T](TemplateControl containerControl, String ControlSrc) in D:\a\1\s\DNN Platform\Library\UI\ControlUtilities.cs:line 99
   at DotNetNuke.UI.Skins.Skin.LoadSkin(PageBase page, String skinPath) in D:\a\1\s\DNN Platform\Library\UI\Skins\Skin.cs:line 691
   --- End of inner exception stack trace ---
2021-12-04 21:12:52,145 [JFDell][Thread:34][ERROR] DotNetNuke.Services.Exceptions.Exceptions - DotNetNuke.Services.Exceptions.PageLoadException: Unhandled error loading page. ---> System.InvalidOperationException: No service for type 'DotNetNuke.UI.Modules.IModuleControlPipeline' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at DotNetNuke.UI.Skins.Skin..ctor() in D:\a\1\s\DNN Platform\Library\UI\Skins\Skin.cs:line 71
   at ASP.portals__default_skins_xcillion_inner_ascx..ctor()
   at __ASP.FastObjectFactory_app_web_bqvi0ido.Create_ASP_portals__default_skins_xcillion_inner_ascx()
   at System.Web.Compilation.BuildResultCompiledType.CreateInstance()
   at System.Web.UI.TemplateControl.LoadControl(IWebObjectFactory objectFactory, VirtualPath virtualPath, Type t, Object[] parameters)
   at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath)
   at DotNetNuke.UI.ControlUtilities.LoadControl[T](TemplateControl containerControl, String ControlSrc) in D:\a\1\s\DNN Platform\Library\UI\ControlUtilities.cs:line 99
   at DotNetNuke.UI.Skins.Skin.LoadSkin(PageBase page, String skinPath) in D:\a\1\s\DNN Platform\Library\UI\Skins\Skin.cs:line 691
   --- End of inner exception stack trace ---
2021-12-04 21:12:52,153 [JFDell][Thread:34][FATAL] DotNetNuke.Framework.PageBase - An error has occurred while loading page.
System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetNuke.UI.Skins.Skin.GetSkin(PageBase page) in D:\a\1\s\DNN Platform\Library\UI\Skins\Skin.cs:line 429
   at DotNetNuke.Framework.DefaultPage.OnInit(EventArgs e) in D:\a\1\s\DNN Platform\Website\Default.aspx.cs:line 193
   at System.Web.UI.Control.<InitRecursiveAsync>d__225.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
2021-12-04 21:12:52,183 [JFDell][Thread:34][ERROR] DotNetNuke.Services.Exceptions.Exceptions - ~/Default.aspx?tabid=3442&error=Object+reference+not+set+to+an+instance+of+an+object.&content=0
System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetNuke.UI.Skins.Skin.GetSkin(PageBase page) in **D:\a\1\s\DNN Platform\Library\UI\Skins\Skin.cs:line 429**
   at DotNetNuke.Framework.DefaultPage.OnInit(EventArgs e) in D:\a\1\s\DNN Platform\Website\Default.aspx.cs:line 193
   at System.Web.UI.Control.<InitRecursiveAsync>d__225.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
2021-12-04 21:12:52,206 [JFDell][Thread:34][FATAL] DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - DotNetNuke.Services.Exceptions.PageLoadException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetNuke.UI.Skins.Skin.GetSkin(PageBase page) in D:\a\1\s\DNN Platform\Library\UI\Skins\Skin.cs:line 429
   at DotNetNuke.Framework.DefaultPage.OnInit(EventArgs e) in D:\a\1\s\DNN Platform\Website\Default.aspx.cs:line 193
   at System.Web.UI.Control.<InitRecursiveAsync>d__225.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
   --- End of inner exception stack trace ---

**To Reproduce**

**Expected behavior**

**Current behavior**
A clear and concise description of what is currently happening.

**Screenshots**

**Additional context**
Add any other context about the problem here including the Browser/OS version.

**Comment by mksmanish79** [comment]
We are unable to duplicate the issue. Can you please provide us more details so that we can duplicate the issue.?
